### ISSUE TITLE
deepspeed.initialize OOM

### ISSUE THREAD

**Issue by wuzhiye7** [baichuan-inc/Baichuan2#113]
A100 80G 全参数微调 Baichuan2-13B-Chat  模型加载没问题， deepspeed.initialize时报错OOM

具体报错在：
self.optimizer.step()

2023-09-14 21:27:58.000 [INFO] [Driver] model, optimizer, _, _ = deepspeed.initialize(
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] engine = DeepSpeedEngine(args=args,
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] self._configure_optimizer(optimizer, model_parameters)
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1209, in _configure_optimizer
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] self.optimizer = self._configure_zero_optimizer(basic_optimizer)
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1505, in _configure_zero_optimizer
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] optimizer = DeepSpeedZeroOptimizer_Stage3(
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 322, in __init__
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] self._setup_for_real_optimizer()
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 418, in _setup_for_real_optimizer
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] self.initialize_optimizer_states()
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 928, in initialize_optimizer_states
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] self._optimizer_step(i)
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 853, in _optimizer_step
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] self.optimizer.step()
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] return func(*args, **kwargs)
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 157, in step
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] state['exp_avg_sq'] = torch.zeros_like(p.data)
2023-09-14 21:27:58	2023-09-14 21:27:58.000 [INFO] [Driver] RuntimeError: CUDA out of memory. Tried to allocate 3.80 GiB (GPU 1; 79.35 GiB total capacity; 76.79 GiB already allocated; 1.02 GiB free; 76.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

想问下，全量微调baichuan2-13B大概需要多少G显存？

**Comment by icoderzqliu** [comment]
请问你的问题怎么解决的？我也遇到这个问题了

**Comment by Crystalxd** [comment]
I solved it by updating the version of deepspeed from 0.8.x to >=0.9.5.
