### ISSUE TITLE
用llama.cpp来加速baichuan2出错

### ISSUE THREAD

**Issue by dansinboy** [baichuan-inc/Baichuan2#151]
会显示cuda报错，有没有人知道如何使用llama.cpp来加速baichuan2模型的推理吗？transformers实在是太慢了

**Comment by jameswu2014** [comment]
应该是可以的。

**Comment by dereklll** [comment]
CUDA error 9 at ggml-cuda.cu:6829: invalid configuration argument
current device: 0


同样的问题，cpu可以正常推理，GPU就会报以上错，能帮忙解决一下吗？

**Comment by 948024326** [comment]
> CUDA error 9 at ggml-cuda.cu:6829: invalid configuration argument current device: 0
> 
> 同样的问题，cpu可以正常推理，GPU就会报以上错，能帮忙解决一下吗？ @ [jameswu2014](https://github.com/jameswu2014) @dansinboy

请问您解决了嘛？ 碰到了同样的问题

**Comment by 948024326** [comment]
> CUDA error 9 at ggml-cuda.cu:6829: invalid configuration argument current device: 0
> 
> 同样的问题，cpu可以正常推理，GPU就会报以上错，能帮忙解决一下吗？ @ [jameswu2014](https://github.com/jameswu2014) @dansinboy

@dereklll 请问您解决了嘛？ 碰到了同样的问题
